### ISSUE TITLE
ERROR: Miasma::Error::ApiError::RequestError: Forbidden - InvalidClientTokenId on "sfn describe"

### ISSUE THREAD

**Issue by cixelsyd** [miasma-rb/miasma-aws#21] opened 2015-10-05 17:40 UTC
Hello.  I worked with you the other week to troubleshoot some issues with the implementation of AWS's STS, and although some things are working properly, some things are still not working correctly.  I am able to successfully run "sfn list", "sfn destroy", and "sfn inspect"... however, when I run "sfn create STACK --apply-stack=OTHERSTACK" I receive the error message above.  I also receive the error message when I run "sfn describe ROOTSTACK" on a stack that contains nested stacks.

Thanks for your help!

**Comment by chrisroberts** [comment] 2015-10-05 17:43
The issue is within the resource expansion functionality attempting to rebuild the API connection and using the STS provided key id/secret to request new tokens (which properly fails).

**Comment by imbriaco** [comment] 2015-10-06 17:46
I'm seeing something similar that I think is probably related. I'm able to run `sfn inspect` but when I try to do `sfn inspect -n` I get the same permission error above. It looks like the original credentials are not being saved, even with the `fix/api-for-sts` branch. I'm investigating further on my end as well and will report back when I figure out what's going on.

**Comment by chrisroberts** [comment] 2015-10-06 17:49
Hi! Yep, it's the same problem in that the `api_for` isn't setting thing up correctly for newly built API connections. It should be resolved once I get this wrapped up.

**Comment by imbriaco** [comment] 2015-10-06 18:27
FWIW, this seems to resolve it for me. I took the simple expedient of adding the `_original` versions of the access key ID and secret key as attributes, then I save them when a role gets assumed. If this is helpful, I'm happy to turn this into a PR, just let me know. If you plan to fix it another way I'll just consider this a temporary hack to solve my problem until you get there. :) 

https://github.com/imbriaco/miasma-aws/commit/95c5347ac0ad19f73c89f097fd48adad3b7e6bbf

**Comment by chrisroberts** [comment] 2015-10-06 18:30
hahaha, :+1:. This is the exact changeset I currently have locally to get it working. I'm trying to work around setting them as attributes though as they are an internal functionality thing. Feel free to send a PR over. If I can't easily implement it via an available callback on the subclass, the attributes will have to be the answer. Thanks!

**Comment by imbriaco** [comment] 2015-10-06 19:38
Sounds good. Stashing them in an attribute felt like the least icky thing to do and was at least intention revealing when you read the assume_role code. 

I created #22 against the `develop` branch.

**Comment by chrisroberts** [comment] 2015-10-06 23:28
Fix is released in 0.1.28. Thanks so much!

**Closed as completed by chrisroberts** 2015-10-06 23:28 UTC
Labels: bug
